version: '3'
services:
  db:
    image: postgres
    env_file: .env
  content-api:
    build: content-api
    ports:
      - "4567:4567"
  rails-app:
    build: rails-app
    command: ./start.sh
    volumes:
      - ./rails-app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - content-api
    env_file: .env
  worker:
    build: worker
    env_file: .env
    depends_on:
      - db
