apiVersion: v1
kind: Service
metadata:
  name: content-api-service
  labels:
    app: content-api-service
spec:
  type: {{ .Values.contentapi.service.type }}
  ports:
    - port: {{ .Values.contentapi.service.port }}
      targetPort: {{ .Values.contentapi.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: content-api
